
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          # 1. Construimos para la arquitectura que AWS App Runner necesita (amd64)
          docker build --platform linux/amd64 -t willytpfw/appevents:DEV .
          
          # 2. Subimos la imagen ya autenticados
          docker push willytpfw/appevents:DEV
